datasets:
  identify_rsna: ## check this
    data_type: images
    build_info:
      image_path: /ibex/project/c2106/RSNA/RSNA-bbox-1024
      ann_path: /ibex/project/c2106/json_files/RSNA/RSNA_train.json